New option --generator: supports just make and ninja for now.

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -33,7 +33,7 @@ function usage() {
   fi
   (( exitval = ${1:-1} ))
   cat 1>&2 <<EOF
-usage: ${prog} [<mode-options>] [<misc-options>] [--] [<make-build-options>]
+usage: ${prog} [<mode-options>] [<misc-options>] [--] [<generator-build-options>]
        ${prog} --help|-h
 
 Mode options: [-C|--cmake-only|-A|--all|--info] ||
@@ -46,7 +46,8 @@ Misc options: [-D<CMake-definition>]+ [-I|--install-prefix <install-location>]
               [--cmake-debug] [--cmake-trace]
               [--deleted-header[s] <header>[,<header>]+]
               [-f|--force-top]
-              [-g|--grapviz=<dot-file> [--gfilt <gfilt-opt>[,<gfilt-opt>]+]]
+              [-g|--graphviz=<dot-file> [--gfilt <gfilt-opt>[,<gfilt-opt>]+]]
+              [[--generator <generator>]]
               [-j #] [-l|--log[=<log-file>]|--log-file[=<log-file>]]
               [-q|--quiet] [--tee]
               [--test-groups|--groups <group>[<;|,><group>]+]
@@ -121,7 +122,7 @@ CETPKG_BUILD directory).
   procedure will ensure that all build targets are up to date so the
   explicit build option is deactivated. However, you *may* wish to
   specify --build anyway in the case that you wish to pass arguments to
-  the make procedure for the build phase.
+  the generator procedure for the build phase.
 
 --info
 
@@ -187,11 +188,11 @@ MISC. OPTIONS.
 
 --cmake-debug
 
-  Add --debug-output to the cmake command-line options.
+  Add --debug-output to the CMake command line options.
 
 --cmake-trace
 
-  Add --trace to the cmake command-line options.
+  Add --trace to the CMake command line options.
 
 --deleted-header[s] <header>[,<header>]+
 
@@ -216,7 +217,7 @@ MISC. OPTIONS.
 
 --gfilt[=<opt>[,<opt>]+]
 
-  Filter the graphviz output from cmake through cmake-graphviz filt,
+  Filter the graphviz output from CMake through cmake-graphviz-filt,
   with the following options:
 
     exes|no-exes
@@ -248,6 +249,11 @@ MISC. OPTIONS.
   Multiple options should be comma-separated. Note that all of these
   options may be specified in ~/.cgfrc for the same effect (command-line
   overrides).
+
+--generator <generator>
+
+  Use the specified generator. Currently supported values are "make" and
+  "ninja" (default make).
 
 -h|--help
 
@@ -566,7 +572,15 @@ function do_work() {
   if (( ${short_circuit:-0} && ! ${cmake_only:-0} )); then
     announce_stage " SKIPPED per --short-circuit"
     if [[ -n "${cmake_defs}" ]]; then
-      error "WARNING: CMake definitions ignored since CMake not invoked."
+      error "WARNING: CMake definitions ignored since CMake not invoked: ${cmake_defs}"
+    fi
+    if [[ -n "${cmake_debug}" ]] || \
+         [[ -n "${cmake_trace}" ]] || \
+       [[ -n "${generator_arg}" ]]; then
+      error "WARNING: CMake options ignored since CMake not invoked:" \
+            ${cmake_debug+${cmake_debug} } \
+            ${cmake_trace+${cmake_trace} } \
+            ${generator_arg+${generator_arg}}
     fi
   else
     announce_stage
@@ -582,8 +596,8 @@ function do_work() {
           cmd -d "Execute CMake." \
             eval ${ccenv} cmake ${cmake_debug} ${cmake_trace} \
             -DCMAKE_INSTALL_PREFIX="$install_prefix" \
-            -DCMAKE_BUILD_TYPE=$CETPKG_TYPE \
-            $garg ${cmake_defs}${CETPKG_SOURCE}
+            -DCMAKE_BUILD_TYPE=${CETPKG_TYPE} \
+            ${garg} ${cmake_defs}${generator_arg} ${CETPKG_SOURCE}
         }
     ) || check_status # Fail here if there's a problem.
     export -n deleted_headers
@@ -616,7 +630,7 @@ function do_work() {
     stage=build
     maybe_force_top_and_announce
     check_curdir_in_build_tree
-    cmd -d "Execute build. " time make $jarg "$@"
+    cmd -d "Execute build. " time ${generator} ${jarg} "$@"
     check_status
   fi
 
@@ -650,12 +664,14 @@ function do_work() {
   if [[ -n "$targets" ]]; then
     stage="install / package"
     announce_stage
-    ( cd "$CETPKG_BUILD" && cmd -d "Install / test." make $jarg $targets )
+    ( cd "$CETPKG_BUILD" && cmd -d "Install / test." ${generator} $jarg $targets )
     check_status
   fi
 }
 
 # Defaults.
+generator=make
+generator_arg="-G\"Unix Makefiles\""
 log_default="build_`date \"+%Y-%m-%d\"`.log"
 (( tred = 1 ))
 
@@ -673,7 +689,7 @@ if (( $? != 4 )); then
   exit 1
 fi
 
-TEMP=`getopt -n "$prog" --long all,cmake-debug,cmake-only,cmake-trace,install-prefix:,build,clean,clean-logs,deleted-header:,deleted-headers:,force-top,graphviz:,gfilt::,groups:,help,info,install,log::,log-file::,package,quiet,sc,short-circuit,tee,test,test-all,test-groups:,release,verbose -o +ACD:I:RTbcfg:hij:lpqtv -- "${@}"`
+TEMP=`getopt -n "$prog" --long all,cmake-debug,cmake-only,cmake-trace,install-prefix:,build,clean,clean-logs,deleted-header:,deleted-headers:,force-top,generator:,graphviz:,gfilt::,groups:,help,info,install,log::,log-file::,package,quiet,sc,short-circuit,tee,test,test-all,test-groups:,release,verbose -o +ACD:I:RTbcfg:hij:lpqtv -- "${@}"`
 
 if (( $? )); then
   usage 1
@@ -757,7 +773,24 @@ while true; do
       fi
       shift
       ;;
-    -h|--help)
+     --generator)
+      shift
+      case $1 in
+        make)
+            generator_arg="G\"Unix Makefiles\""
+            generator=make
+            ;;
+        ninja)
+            generator_arg=-GNinja
+            generator=ninja
+            ;;
+        *)
+          error "ERROR: Unrecognized generator $1."
+          exit 1
+      esac
+      shift
+      ;;
+     -h|--help)
       usage long
       shift
       ;;
@@ -1006,7 +1039,7 @@ if (( ${quiet:-0} )); then
 fi
 
 if [[ -n "$@" ]]; then
-  report "Extra arguments to make for build stage: $@"
+  report "Extra arguments to $generator for build stage: $@"
 fi
 
 # If we're tee-ing.
