Update buildtool to not mention homebrew.

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -595,7 +595,7 @@ fi
 # Parse arguments.
 getopt -T >/dev/null 2>&1
 if (( $? != 4 )); then
-  echo "ERROR: GNU getopt required! Obtain from homebrew (http://brew.sh)." 1>&2
+  echo "ERROR: GNU getopt required! Check SETUP_GETOPT and PATH." 1>&2
   exit 1
 fi
 
