short-circuit and clean do not make sense.

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -544,6 +544,11 @@ while true; do
   esac
 done
 
+if (( ${clean:-0} && ${short_circuit:-0} )); then
+    echo "ERROR: specifying clean and short-circuit options together is not meaningful." 1>&2
+    exit 1
+fi
+
 # Set test_groups variable based on set options.
 cmake_defs="${cmake_defs}-DCET_TEST_GROUPS=${test_groups} "
 
