Get info from report_product_info where possible.

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -17,9 +17,15 @@ function set_pwd_P_arg() {
 }
 
 function real_dir() {
-    [[ -n "$1" ]] || return 1
-    ( cd "$1" >/dev/null 2>&1 && /bin/pwd ${pwd_P_arg} 2>/dev/null; exit $? )
-    return $?
+  [[ -n "$1" ]] || return 1
+  ( cd "$1" >/dev/null 2>&1 && /bin/pwd ${pwd_P_arg} 2>/dev/null; exit $? )
+  return $?
+}
+
+function set_vars_from_report_file() {
+  type report_product_info >/dev/null 2>&1 || \
+    { echo "ERROR: Unable to find report_product_info: source setup_for_development?" 1>&2; exit 1; }
+  eval $(report_product_info "${CETPKG_BUILD}" all)
 }
 
 # Make sure we can use pwd properly.
@@ -55,7 +61,7 @@ Misc options: [-D<CMake-definition>]+ [-I|--install-prefix <install-location>]
 
 Options suffixed with '+' are repeatable and cumulative.
 
-Required environment: CETPKG_BUILD, CETPKG_SOURCE, CETPKG_TYPE
+Required environment: CETPKG_BUILD
 Optional environment: CETPKG_INSTALL CETPKG_J CETPKG_QUAL
 EOF
   (( ${long:-0} )) && cat 1>&2 <<EOF
@@ -63,12 +69,9 @@ EOF
 
 DETAILS.
 
-The following environment variables *must* be set:
+Required environment variables:
 
 CETPKG_BUILD:   The build area for the current package.
-CETPKG_SOURCE:  The source area for the current package (containing the
-                top-level CMakeLists.txt).
-CETPKG_TYPE:    The build type, required by CMake.
 
 Optional environment variables:
 
@@ -79,8 +82,18 @@ CETPKG_INSTALL: The default location of the private (or public) UPS
                 CMake.
 CETPKG_J:       Default parallelism for all appropriate steps, assuming
                 -j is not specified explicitly.
-CETPKG_QUAL:    If set, causes -Dqualifier:STRING=$CETPKG_QUAL to be
-                added to the CMake arguments.
+
+Other configuration items;
+
+The following items are obtained from the package's
+cetpkg_variable_report file, which is generated by sourcing
+setup_for_development:
+
+CETPKG_SOURCE:  The source area for the current package (containing the
+                top-level CMakeLists.txt).
+CETPKG_TYPE:    The build type, required by CMake.
+CETPKG_QUAL:    If set, causes -Dqualifier:STRING=\$CETPKG_QUAL to be added
+                to the CMake arguments.
 
 
 MODE OPTIONS.
@@ -729,7 +742,7 @@ while true; do
 done
 
 # Basic safety checks.
-if [[ -z "$CETPKG_BUILD" ]] || [[ -z "$CETPKG_SOURCE" ]] || [[ -z "$CETPKG_TYPE" ]]; then
+if [[ -z "$CETPKG_BUILD" ]]; then
   echo "ERROR: Expected CETPKG_BUILD and friends to be set: source setup_for_development?" 1>&2
   exit 1
 elif [[ ! -d "$CETPKG_BUILD" ]] || [[ ! -w "$CETPKG_BUILD" ]]; then
@@ -760,6 +773,12 @@ elif [[ $(real_dir "$CETPKG_BUILD") == "${HOME}" ]] || \
   exit 1
 fi
 
+set_vars_from_report_file()
+
+if [[ -z "$CETPKG_SOURCE" ]] || [[ -z "$CETPKG_TYPE" ]] || [[ -z "$CETPKG_COMPILER" ]]; then
+  echo "ERROR: Missing required variable from cetpkg_variable_report: cetbuildtools version mismatch?" 1>&2
+  exit 1
+fi
 
 # Upcase test groups.
 [[ -n "$test_groups" ]] && \
