test groups -> CMake labels.
Conflicts:
	Modules/CetTest.cmake
	ups/product_deps

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -42,19 +42,28 @@ Mode options: [-C|--cmake-only|-A|--all|--info] ||
 
 Combo options: [-R|--release] || [-T|--test-all]
 
-Misc options: [-D<CMake-definition>]+ [-I|--install-prefix <install-location>]
-              [-c|--clean] [--clean-logs]
-              [--cmake-debug] [--cmake-trace]
+Misc options: [-D<CMake-definition>]+
+              [-I|--install-prefix <install-location>]
+              [--L <label-regex>]
+              [--LE <label-regex>]
+              [-c|--clean]
+              [--clean-logs]
+              [--cmake-debug]
+              [--cmake-trace]
               [--deleted-header[s] <header>[,<header>]+]
               [-f|--force-top]
               [-g|--graphviz=<dot-file> [--gfilt <gfilt-opt>[,<gfilt-opt>]+]]
               [[--generator <generator>]]
-              [-j #] [-l|--log[=<log-file>]|--log-file[=<log-file>]]
-              [-q|--quiet] [-s|--subdir] [--tee]
-              [--test-groups|--groups <group>[<;|,><group>]+]
+              [-j #]
+              [-l|--log[=<log-file>]|--log-file[=<log-file>]]
+              [-q|--quiet]
+              [-s|--subdir]
+              [--tee]
+              [--test-labels|--labels|--test-groups|--groups <group>[<;|,><group>]+]
               [-v|--verbose]
 
-Options suffixed with '+' are repeatable and cumulative.
+Options suffixed with '+' are repeatable and cumulative. If a
+non-repeatable option is specified multiple times, last invocation wins.
 
 Required environment: CETPKG_BUILD
 Optional environment: CETPKG_INSTALL CETPKG_J CETPKG_QUAL
@@ -154,12 +163,12 @@ COMBO MODE OPTIONS.
 -R
 --release
 
-  Equivalent to -t --test-groups=RELEASE.
+  Equivalent to -t --test-labels=RELEASE.
 
 -T
 --test-all
 
-  Equivalent to -t --test-groups=ALL.
+  Equivalent to -t --test-labels=ALL.
 
 
 MISC. OPTIONS.
@@ -177,6 +186,13 @@ MISC. OPTIONS.
   which to install the package if install is requested. Overrides the
   CETPKG_INSTALL environment variable and anything already known to
   CMake.
+
+--L <label-regex>
+--LE <label-regex>
+
+  Per CTest, include (--L) or exclude (--LE) labels by CMake regex. Both
+  options are mutually exclusive with --test-labels, -T and -R, but not
+  with each other. Specifying one of these options implies -t.
 
 -c
 --clean
@@ -300,14 +316,20 @@ MISC. OPTIONS.
   Write to a log file (either as specified by --log or the default), but
   copy output to the screen also: --quiet is overridden by this option.
 
+--test-labels <group>[<;|,><group>]+
+--labels <group>[<;|,><group>]+
 --test-groups <group>[<;|,><group>]+
 --groups <group>[<;|,><group>]+
 
-  Specify optional test groups to configure per cet_test macro
-  (CetTest.cmake). Equivalent to -DCET_TEST_GROUPS=... if multiple
-  groups are delimited with semicolons they should be escaped or
-  quoted to protect them from the shell. A warning shall be issued if
-  this option is specified but the CMake stage is not to be executed.
+  Specify optional CMake test labels to execute. Since cetbuildtools
+  v6_00_00, this is integrated with the CMake labels facility, and the
+  test selection is done at CTest invocation time rather than CMake time
+  as previously. If this option is activated but tests are not to be
+  run, a warning shall be issued. If no labels are selected, then
+  DEFAULT is selected. A value of ALL is substituted with all known test
+  labels. A leading `-' for a label will lead to its explicit
+  exclusion. See also -T, -R options. Mutually-exclusive with --L and
+  --LE options.
 
 --usage
 
@@ -367,12 +389,15 @@ function package_version() {
   echo "$(cmake_var VERSION_MAJOR).$(cmake_var VERSION_MINOR).$(cmake_var VERSION_PATCH)"
 }
 
-function package_test_groups() {
-  cmake_var CET_DEFINED_TEST_GROUPS | sed -e 's&;&, &g'
+function cmake_to_bash_list() {
+  local OIFS=$IFS
+  IFS=\;
+  bash_list=(${@})
+  IFS=$OIFS
 }
 
-function selected_test_groups() {
-  cmake_var CET_TEST_GROUPS | sed -e 's&;&, &g'
+function package_test_labels() {
+  cmake_var CET_DEFINED_TEST_GROUPS
 }
 
 function basic_info() {
@@ -382,15 +407,11 @@ Package info:           $(package_name) $(package_version)
 Build type:             $(cmake_var CMAKE_BUILD_TYPE)
 Qualifier:              $(cmake_var qualifier)
 EOF
-    local defined_test_groups=$(package_test_groups)
-    [[ -n "$defined_test_groups" ]] && \
+    cmake_to_bash_list "$(package_test_labels)"
+    local defined_test_labels="${bash_list[@]}"
+    [[ -n "{$defined_test_labels[@]}" ]] && \
       cat <<EOF
-Known test groups:      ${defined_test_groups}
-EOF
-    local selected_test_groups=$(selected_test_groups)
-    [[ -n "$selected_test_groups" ]] && \
-      cat <<EOF
-Selected test groups:   ${selected_test_groups}
+Known test groups:      ${defined_test_labels[@]}
 EOF
     exit 0
   else
@@ -404,15 +425,10 @@ function package_info() {
   local package_version=$(package_version)
   [[ -n "$package_name" ]] && [[ -n "$package_version" ]] || return
   local msg="INFO: $package_name version $package_version configured."
-  local test_groups="$(package_test_groups)"
-  [[ -n "$test_groups" ]] && \
+  local test_labels="$(package_test_labels)"
+  [[ -n "$test_labels" ]] && \
     msg="${msg}
-      Available test groups: ${test_groups}."
-  local selected_test_groups=$(selected_test_groups)
-  [[ -n "$selected_test_groups" ]] && \
-    msg="$msg
-      Selected test groups:  ${selected_test_groups}."
-  banner "$msg"
+      Available test groups: ${test_labels}."
   (( ${redirected:-0} )) && printf -- "$msg\n" 1>&3
 }
 
@@ -593,6 +609,42 @@ function reorder_quals() {
   printf -- "$1" | tr ':' '\n' | sort | tr '\n' ':' | sed -e 's/:$//'
 }
 
+function label_regex() {
+  if (( $# )); then
+    ans='^('
+    for label in "${@}"; do
+      ans="${ans}${label}|"
+    done
+    ans="${ans%|})\$"
+    printf "${ans}"
+  fi
+}
+
+function test_spec_args() {
+  tsargs=()
+  if [[ -n "${test_labels}" ]]; then
+    cmake_to_bash_list "${test_labels}"
+    local l=()
+    local le=()
+    for label in "${bash_list[@]}"; do
+      if [[ "$(echo "${label#-}" | tr '[a-z]' '[A-Z]')" = "ALL" ]]; then
+        # Short-circuit
+        tsargs=()
+        return
+      fi
+      if [[ "${label}" == -* ]]; then
+        le+=("${label#-}")
+      else
+        l+=("${label}")
+      fi
+      local l_regex=$(label_regex "${l[@]}")
+      local le_regex=$(label_regex "${le[@]}")
+    done
+  fi
+  tsargs=(${l_regex:+-L "${l_regex}"} ${le_regex:+-LE "${le_regex}"})
+  (( ${#tsargs[@]} == 0 )) && tsargs=(-L '^DEFAULT$')
+}
+
 # Main work
 function do_work() {
   local real_subdir
@@ -700,10 +752,13 @@ function do_work() {
     fi
     maybe_force_top_and_announce
     check_curdir_in_build_tree
+    test_spec_args
     # Trap and tee *only* stderr from ctest. Yes, this is fiddly.
     exec 5>&1
     { cmd -d "Execute tests." \
-      ctest $jarg 2>&1 >&5 5>&-; echo $? > "$TMP/status.dat"; } | \
+      ctest $jarg "${tsargs[@]}" 2>&1 >&5 5>&-
+      echo $? > "$TMP/status.dat"
+    } | \
      tee "$TMP/ctest.err" 5>&-
     exec 5>&-
     local status
@@ -721,6 +776,13 @@ function do_work() {
     else
       check_status $status
     fi
+  elif [[ -n "${test_labels}${l_regex}${le_regex}" ]]; then
+    test_specs="${test_labels:+--test-labels ${test_labels}}"
+    if [[ -z "${test_specs}" ]]; then
+      test_specs="${l_regex:+--L \"${l_regex}\"}"
+      [[ -n "${le_regex}" ]] && test_specs="${test_specs:+${test_specs} }--LE \"${le_regex}\""
+    fi
+    error "WARNING: test label specifications ${test_specs} ignored since tests are not enabled."
   fi
 
   if [[ -n "$targets" ]]; then
@@ -749,7 +811,7 @@ if (( $? != 4 )); then
   exit 1
 fi
 
-TEMP=`getopt -n "$prog" --long all,cmake-debug,cmake-only,cmake-trace,install-prefix:,build,clean,clean-logs,deleted-header:,deleted-headers:,force-top,generator:,graphviz:,gfilt::,groups:,help,info,install,log::,log-file::,package,quiet,sc,short-circuit,subdir:,tee,test,test-all,test-groups:,release,usage,verbose -o +ACD:I:RTbcfg:hij:lpqs:tv -- "${@}"`
+TEMP=`getopt -n "$prog" --long L:,LE:,all,cmake-debug,cmake-only,cmake-trace,install-prefix:,build,clean,clean-logs,deleted-header:,deleted-headers:,force-top,generator:,graphviz:,gfilt::,groups:,help,info,install,labels:,log::,log-file::,package,quiet,sc,short-circuit,subdir:,tee,test,test-all,test-labels:,test-groups:,release,usage,verbose -o +ACD:I:RTbcfg:hij:lpqs:tv -- "${@}"`
 
 if (( $? )); then
   usage 1
@@ -781,13 +843,25 @@ while true; do
       shift
       shift
       ;;
+    --L)
+      l_regex=$2
+      shift
+      shift
+      set -- -t "${@}"
+      ;;
+    --LE)
+      le_regex=$2
+      shift
+      shift
+      set -- -t "${@}"
+      ;;
     -R|--release)
       shift
-      set -- -t --test-groups RELEASE "${@}"
+      set -- -t --test-labels RELEASE "${@}"
       ;;
     -T|--test-all)
       shift
-      set -- -t --test-groups ALL "${@}"
+      set -- -t --test-labels ALL "${@}"
       ;;
     -b|--build)
       (( do_build = 1 ))
@@ -909,12 +983,8 @@ while true; do
       (( tee = 1 ))
       shift
       ;;
-    --test-groups|--groups)
-      if [[ -n "$test_groups" ]]; then
-        test_groups="${test_groups};${2}"
-      else
-        test_groups="${2}"
-      fi
+    --test-labels|--labels|--test-groups|--groups)
+      test_labels="${test_labels:+${test_labels};}${2//,/;}"
       shift
       shift
       ;;
@@ -983,6 +1053,7 @@ if [[ -z "$CETPKG_SOURCE" ]] || \
   exit 1
 fi
 
+# Argument consistency checks
 if (( ${clean:-0} )) && [[ -n "${MRB_BUILDDIR}" ]]; then
   echo "ERROR: MRB environment detected. Use mrb z; mrb setenv instead of buildtool (or mrb b) --clean" 1>&2
   exit 1
@@ -993,12 +1064,11 @@ if (( ${force_top:-0} )) && [[ -n "${subdir}" ]]; then
     exit 1
 fi
 
-# Upcase test groups.
-[[ -n "$test_groups" ]] && \
-  test_groups=$(echo "$test_groups" | tr '[a-z]' '[A-Z]')
-
-# Set test_groups variable based on set options.
-cmake_defs="${cmake_defs}-DCET_TEST_GROUPS=${test_groups} "
+if [[ -n "${test_labels}" ]] && \
+   { [[ -n "${l_regex}" ]] || [[ -n "${le_regex}" ]]; }; then
+  echo "ERROR: --LE and --L are mutually-exclusive with -T, -R, and --test-labels and synonyms." 1>&2
+  exit 1
+fi
 
 # If desired, print current build information and quit.
 if (( ${want_info:-0} )); then
