General cleanup.

diff --git a/bin/buildtool b/bin/buildtool
--- a/bin/buildtool
+++ b/bin/buildtool
@@ -281,11 +281,15 @@ function restore_output_streams() {
   fi
 }
 
+function cleanup() {
+  [[ -n "$TMP" ]] && [[ -d "$TMP" ]] && rm -rf "$TMP"
+}
+
 # Main work
 function do_work() {
   if log_no_tee; then
     exec 3>&1 4>&2 >"$log" 2>&1
-    trap "restore_output_streams" EXIT
+    trap "restore_output_streams; cleanup" EXIT
   fi
 
   stage=cmake
@@ -438,7 +442,7 @@ if (( ${clean:-0} )); then
     echo "ERROR: Clean operation would remove the current directory!" 1>&2
     exit 2
   fi
-  trap "f=$?; printf \"\nAborted\n\" 1>&2; exit $f" 2
+  trap "f=$?; printf \"\nAborted\n\" 1>&2; cleanup; exit $f" 2
   printf "INFO: About to clean \"$CETPKG_BUILD\": ctrl-C to abort within 5 seconds "
   for i in 1 2 3 4 5; do printf "."; sleep 1; done
   printf "\n";
